name: Overpass to GeoJSON

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: fetch and convert OSM Overpass data
        run: |
          pip install -r requirements.txt
          python main.py
      - name: upload GeoJSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: fr-37-bike-parking-stations.geojson
          path: output.geojson
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: fr-37-bike-parking-stations.geojson
          overwrite: true
    
    
    
