name: Overpass to GeoJSON

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: fetch and convert OSM Overpass data
        run: |
          pip install -r requirements.txt
          python main.py
      - name: upload GeoJSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: fr-37-bike-parking-stations.geojson
          path: output.geojson
  upload:
    runs-on: ubuntu-latest
    needs: run
    steps:
      - name: retrieve GeoJSON artifact
        uses: actions/download-artifact@v4
        with:
          name: fr-37-bike-parking-stations.geojson
          path: stationnement-cyclable-gares-serm.geojson
      - name: Upload artifact to data.gouv
        env:
          DATA_GOUV_API_KEY: ${{ secrets.DATA_GOUV_API_KEY }}
        run: |
            curl -H "Accept:application/geo+json" -H "X-Api-Key:$DATA_GOUV_API_KEY" -F "file=@stationnement-cyclable-gares-serm.geojson" \
             -X POST "$DATA_GOUV_API/datasets/$DATA_GOUV_DATASET/resources/$DATA_GOUV_RESOURCE/upload/"
    
    
    
